#!/bin/bash
set -o errexit
set -o xtrace

mkdir build
cd build

git clone --single-branch --branch master https://github.com/jupyterlab/lumino
cd lumino
git checkout 4f2432290e874b040310d428593abe4afc336066
jlpm
jlpm build
for package in packages/*; do
  ( cd "$package" && jlpm link )
done
cd ..

git clone --single-branch --branch master https://github.com/jupyterlab/jupyterlab.git
cd jupyterlab
git checkout c91e1ea89c822cd292989a82222aef7a4dcfe1c3
jlpm
# link all lumino packages by assming their npm packge name is "@lumino/" prepepended to their folder name
jlpm link $(ls ../lumino/packages | sed -e 's/^/@lumino\//')
jlpm run build:dev
jupyter lab build
pip install -e .
cd ../..